const directory = [
  {
    text: "C 语言教程",
    collapsed: false,
    items: [
      { text: "简介", link: "/tutorial/C/intro" },
      { text: "基本语法", link: "/tutorial/C/syntax" },
      { text: "变量", link: "/tutorial/C/variable" },
      { text: "运算符", link: "/tutorial/C/operator" },
      { text: "流程控制", link: "/tutorial/C/flow-control" },
      { text: "数据类型", link: "/tutorial/C/types" },
      { text: "指针", link: "/tutorial/C/pointer" },
      { text: "函数", link: "/tutorial/C/function" },
      { text: "数组", link: "/tutorial/C/array" },
      { text: "字符串", link: "/tutorial/C/string" },
      { text: "内存管理", link: "/tutorial/C/memory" },
      { text: "struct 结构", link: "/tutorial/C/struct" },
      { text: "typedef 命令", link: "/tutorial/C/typedef" },
      { text: "Union 结构", link: "/tutorial/C/union" },
      { text: "Enum 类型", link: "/tutorial/C/enum" },
      { text: "预处理器", link: "/tutorial/C/preprocessor" },
      { text: "I/O 函数", link: "/tutorial/C/io" },
      { text: "文件操作", link: "/tutorial/C/file" },
      { text: "变量说明符", link: "/tutorial/C/specifier" },
      { text: "多文件项目", link: "/tutorial/C/multifile" },
      { text: "命令行环境", link: "/tutorial/C/cli" },
      { text: "多字节字符", link: "/tutorial/C/multibyte" },
    ],
  },
  {
    text: "标准库",
    collapsed: false,
    items: [
      { text: "assert.h", link: "/tutorial/C/lib/assert.h" },
      { text: "ctype.h", link: "/tutorial/C/lib/ctype.h" },
      { text: "errno.h", link: "/tutorial/C/lib/errno.h" },
      { text: "float.h", link: "/tutorial/C/lib/float.h" },
      { text: "inttypes.h", link: "/tutorial/C/lib/inttypes.h" },
      { text: "iso646.h", link: "/tutorial/C/lib/iso646.h" },
      { text: "limits.h", link: "/tutorial/C/lib/limits.h" },
      { text: "locale.h", link: "/tutorial/C/lib/locale.h" },
      { text: "math.h", link: "/tutorial/C/lib/math.h" },
      { text: "signal.h", link: "/tutorial/C/lib/signal.h" },
      { text: "stdarg.h", link: "/tutorial/C/lib/stdarg.h" },
      { text: "stdbool.h", link: "/tutorial/C/lib/stdbool.h" },
      { text: "stddef.h", link: "/tutorial/C/lib/stddef.h" },
      { text: "stdint.h", link: "/tutorial/C/lib/stdint.h" },
      { text: "stdlib.h", link: "/tutorial/C/lib/stdlib.h" },
      { text: "stdio.h", link: "/tutorial/C/lib/stdio.h" },
      { text: "string.h", link: "/tutorial/C/lib/string.h" },
      { text: "time.h", link: "/tutorial/C/lib/time.h" },
      { text: "wchar.h", link: "/tutorial/C/lib/wchar.h" },
      { text: "wctype.h", link: "/tutorial/C/lib/wctype.h" },
    ],
  },
];

export default directory;
