bindPort = 8800
vhostHTTPPort = 8088
auth.method = "token"
auth.token = "your-secret-token888"

#限制直接使用frp的8088端口直接访问（因为配置了caddy,可以直接80端口访问）
proxyBindAddr = "127.0.0.1"

# frpc 单向校验 frps 身份
transport.tls.certFile = "/etc/frp/server.crt"
transport.tls.keyFile = "/etc/frp/server.key"