const directory = [
  {
    text: "Bash 教程",
    collapsed: false,
    items: [
      { text: "简介", link: "/tutorial/Bash/intro" },
      { text: "基本语法", link: "/tutorial/Bash/grammar" },
      { text: "模式扩展", link: "/tutorial/Bash/expansion" },
      { text: "引号和转义", link: "/tutorial/Bash/quotation" },
      { text: "变量", link: "/tutorial/Bash/variable" },
      { text: "字符串操作", link: "/tutorial/Bash/string" },
      { text: "算术运算", link: "/tutorial/Bash/arithmetic" },
      { text: "操作历史", link: "/tutorial/Bash/history" },
      { text: "行操作", link: "/tutorial/Bash/readline" },
      { text: "目录堆栈", link: "/tutorial/Bash/stack" },
      { text: "脚本入门", link: "/tutorial/Bash/script" },
      { text: "read 命令", link: "/tutorial/Bash/read" },
      { text: "条件判断", link: "/tutorial/Bash/condition" },
      { text: "循环", link: "/tutorial/Bash/loop" },
      { text: "函数", link: "/tutorial/Bash/function" },
      { text: "数组", link: "/tutorial/Bash/array" },
      { text: "set 命令，shopt 命令", link: "/tutorial/Bash/set" },
      { text: "脚本除错", link: "/tutorial/Bash/debug" },
      { text: "mktemp 命令，trap 命令", link: "/tutorial/Bash/mktemp" },
      { text: "启动环境", link: "/tutorial/Bash/startup" },
      { text: "命令提示符", link: "/tutorial/Bash/prompt" },
    ],
  },
  {
    text: "命令笔记",
    collapsed: false,
    items: [
      { text: "alias", link: "/tutorial/Bash/archives/commands/alias" },
      { text: "awk", link: "/tutorial/Bash/archives/commands/awk" },
      { text: "cal", link: "/tutorial/Bash/archives/commands/cal" },
      { text: "cat", link: "/tutorial/Bash/archives/commands/cat" },
      { text: "clear", link: "/tutorial/Bash/archives/commands/clear" },
      { text: "cp", link: "/tutorial/Bash/archives/commands/cp" },
      { text: "cut", link: "/tutorial/Bash/archives/commands/cut" },
      { text: "date", link: "/tutorial/Bash/archives/commands/date" },
      { text: "dd", link: "/tutorial/Bash/archives/commands/dd" },
      { text: "df", link: "/tutorial/Bash/archives/commands/df" },
      { text: "du", link: "/tutorial/Bash/archives/commands/du" },
      { text: "egrep", link: "/tutorial/Bash/archives/commands/egrep" },
      { text: "export", link: "/tutorial/Bash/archives/commands/export" },
      { text: "file", link: "/tutorial/Bash/archives/commands/file" },
      { text: "find", link: "/tutorial/Bash/archives/commands/find" },
      { text: "fmt", link: "/tutorial/Bash/archives/commands/fmt" },
      { text: "grep", link: "/tutorial/Bash/archives/commands/grep" },
      { text: "gunzip", link: "/tutorial/Bash/archives/commands/gunzip" },
      { text: "gzcat", link: "/tutorial/Bash/archives/commands/gzcat" },
      { text: "gzip", link: "/tutorial/Bash/archives/commands/gzip" },
      { text: "kill", link: "/tutorial/Bash/archives/commands/kill" },
      { text: "killall", link: "/tutorial/Bash/archives/commands/killall" },
      { text: "last", link: "/tutorial/Bash/archives/commands/last" },
      { text: "lpq", link: "/tutorial/Bash/archives/commands/lpq" },
      { text: "lpr", link: "/tutorial/Bash/archives/commands/lpr" },
      { text: "ls", link: "/tutorial/Bash/archives/commands/ls" },
      { text: "nl", link: "/tutorial/Bash/archives/commands/nl" },
      { text: "ps", link: "/tutorial/Bash/archives/commands/ps" },
      { text: "scp", link: "/tutorial/Bash/archives/commands/scp" },
      { text: "sed", link: "/tutorial/Bash/archives/commands/sed" },
      { text: "sort", link: "/tutorial/Bash/archives/commands/sort" },
      { text: "tr", link: "/tutorial/Bash/archives/commands/tr" },
      { text: "uname", link: "/tutorial/Bash/archives/commands/uname" },
      { text: "uniq", link: "/tutorial/Bash/archives/commands/uniq" },
      { text: "uptime", link: "/tutorial/Bash/archives/commands/uptime" },
      { text: "w", link: "/tutorial/Bash/archives/commands/w" },
      { text: "wc", link: "/tutorial/Bash/archives/commands/wc" },
      { text: "whereis", link: "/tutorial/Bash/archives/commands/whereis" },
      { text: "which", link: "/tutorial/Bash/archives/commands/which" },
      { text: "who", link: "/tutorial/Bash/archives/commands/who" },
    ],
  },
];

export default directory;
